### ISSUE TITLE
Update job posting design

### ISSUE THREAD

**Issue by dj2** [cds-snc/digital-canada-ca#2126]
The design for the Job posting pages has been updated:

![image](https://user-images.githubusercontent.com/9611/113767453-b222b780-96ec-11eb-9bef-b0ac410d9d95.png)

This could probably be implemented as 3 pieces:
 * [ ] Application Form
 * [ ] Our Hiring Process section
 * [ ] Main job posting section

Questions:
 * Where does the `More about our hiring process` button link too?
 * I'd assume the `H1`, `H2`, etc in the mock are just for info purposes and won't appear in the final page.
 * Is it intentional that the `Resume` label is missing from the browse button? Without the label it's unclear what you're browsing for.

Figma: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-(Copy-w%2F-March-2021-Updates)?node-id=132%3A8007

**Comment by victoriachanimal** [comment]
See CDS website design system (CSS styles) here: https://digital-canada-system.netlify.app/components/detail/color.html

**Comment by victoriachanimal** [comment]
Hey @dj2! Some additional info based on the q's: 

 **_Where does the More about our hiring process button link too?_**
The button will link to the `Careers` page (#2124 )

**_I'd assume the H1, H2, etc in the mock are just for info purposes and won't appear in the final page._**
Yes, the H1 and H2s are for info purposes - they will be used as a guide for teams writing accessible markdown for future job postings

**_Is it intentional that the Resume label is missing from the browse button? Without the label it's unclear what you're browsing for._**
Looping in @amazingphilippe for this question about your thoughts on the Resume label (which is featured on the existing job application form)

**Comment by amazingphilippe** [comment]
>  * Is it intentional that the `Resume` label is missing from the browse button? Without the label it's unclear what you're browsing for.

Definitely an oversight. There should be a label, and maybe some hint text if we have restrictions like file size or type.

**Comment by victoriachanimal** [comment]
Thanks @amazingphilippe ! Added a "Resume" label above the Browse button in [this Figma file,](https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Copy-w-March-2021-Updates?node-id=132%3A8131) feel free to edit further.

**Comment by victoriachanimal** [comment]
English mockup: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Revamp-Work-in-Progress?node-id=132%3A8131
French mockup: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Revamp-Work-in-Progress?node-id=652%3A485
