### ISSUE TITLE
Implement new team page design

### ISSUE THREAD

**Issue by dj2** [cds-snc/digital-canada-ca#2127]
The team page design has been updated:

![image](https://user-images.githubusercontent.com/9611/113767978-4ab93780-96ed-11eb-9827-b9012a0d3a53.png)

There will be some work to update the [team.yml](https://github.com/cds-snc/digital-canada-ca/blob/master/data/team.yml) file to provide context on the role for each person.

Questions:
 * Can a person be in more than one role? Do they have a primary role only?
 * What order do the roles get shown, exec team and then alphabetical (does that mean we'd have different order in English/French?) Or some other ordering?

Figma: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-(Copy-w%2F-March-2021-Updates)?node-id=132%3A8007

**Comment by victoriachanimal** [comment]
Additional info from questions: 

_**Can a person be in more than one role? Do they have a primary role only?**_
I think they definitely can be in more than one role, but in order to help with navigation / clear steps, the plan is to feature someone in their primary community. 

**_What order do the roles get shown, exec team and then alphabetical (does that mean we'd have different order in English/French?) Or some other ordering?_**
The community categories we'll feature on this page include: Leadership, Design, Research (ie. Design Research as our internal category but rephrased on this page for our users), Development, Internal Operations, Partnerships, Policy, Product Management, Outreach, & People and Culture (ie. Talent). 

^ In terms of the ordering, we're planning on featuring Leadership as first on the list, and then alphabetically in English and French. But since English and French would involve a different order as you mentioned, do you think this approach would translate well from a dev standpoint? @dj2

**Comment by dj2** [comment]
From a dev standpoint it shouldn't matter, we get the list, remove leadership and sort it. The sort would be done in the appropriate language, so will work out fine. I was originally thinking it could be confusing for users but then, why would they be looking at it in english and french at the same time, so not an issue.

**Comment by victoriachanimal** [comment]
English mockup: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Revamp-Work-in-Progress?node-id=132%3A7898
French mockup: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Revamp-Work-in-Progress?node-id=672%3A10048
