### ISSUE TITLE
Can the forcing of links to open in _blank be removed?

### ISSUE THREAD

**Issue by dj2** [cds-snc/digital-canada-ca#2142]
We have a few JS files which are doing:

```
// Add target=_blank to external links
$("#wb-cont a[href^='http://']").attr("target","_blank");
$("#wb-cont a[href^='https://']").attr("target","_blank");
```

Can this be removed? Most users can either open in a new window in other mechanisms if desired, but there is no way to open in the current window if we `_blank` everything.

**Comment by dj2** [comment]
@victoriachanimal do you know why we force the `_blank` on links?

**Comment by victoriachanimal** [comment]
@dj2 Hmmm I'm actually not sure as I believe it was implemented when the website was first created / before I got here. One thing that I think may have been a consideration is that we generally have a lot of external links to outside resources, whether it's through our product cards, blogs, etc — but yes, users can open in a new window through other mechanisms, and we don't really have anything on the site where users need this in order to not lose content or work in progress. 

Lmk what you think, but I think we can remove forced `_blank` on links
