### ISSUE TITLE
Blog preview text

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/digital-canada-ca#290]
How might we ensure a blog preview is more than simply the first heading, as is the case in Annie's blog on 'Digital words: mots vs. maux' ?

<img width="919" alt="screen shot 2018-08-21 at 10 37 33 am" src="https://user-images.githubusercontent.com/38330843/44408411-52bd0c80-a52e-11e8-98bf-aac3705b85b3.png">

**Comment by sboots** [comment]
Oooh, good point! One thing we can do is, use the "description" field in the blog post metadata (e.g. [here](https://github.com/cds-snc/digital-canada-ca/blob/master/_posts/en/2018-08-17-lexicon.md)), rather than the first paragraph that it's currently using.

That would be a minor change to the code for the blog post index pages - I could take a look later!

**Comment by sboots** [comment]
I have a draft fix for this here, <https://github.com/cds-snc/digital-canada-ca/commit/9ccb52a594fb56a047f0911f59bd49b0e25504a6>

It'd be good to take a look locally to make sure we're happy with this change from a content standpoint, and to see if we want to adjust any of the blog descriptions in English or French now that they show up more visibly.

**Comment by sboots** [comment]
For example, we may want to shorten this down slightly. 😅 

<img width="1312" alt="screen shot 2018-08-21 at 17 42 20" src="https://user-images.githubusercontent.com/263472/44430868-0ee7f880-a56a-11e8-81db-105d5a563999.png">
