### ISSUE TITLE
HTTPS for digital.canada.ca

### ISSUE THREAD

**Issue by scilib** [cds-snc/digital-canada-ca#6]
https://digital.canada.ca/ doesn't work (gives a certificate error).  (It's because the site is actually a CNAME alias for a Github site.)

github.io pages [support HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/) but there will be a tricky interaction between the digital.canada.ca address and the underlying Github website.  The only examples I could find for https with a custom domain on a github.io site were for CloudFlare.

I would consider https as the default for government websites a best practice, e.g. https://https.cio.gov/

**Comment by mcman12** [comment]
hi @scilib 
we will definitely have https and we are looking into this, now that we exist we've got more options. ;) 
we'll post updates here.
thanks

**Comment by konklone** [comment]
FWIW, down here in 18F, we run https://federalist.18f.gov, which is a static site (Jekyll) building app that builds sites and tosses them into S3. Then we use cloud.gov's CDN/CloudFront integration to deploy a certificate in front of each site hosted on Federalist.

That's not a super trivial thing to port, but it is all open source. :)

Before that, we used to run the site on an EC2 instance, and set up a small webhook so that whenever the GitHub repo was updated, it would ping a little daemon running on the instance (proxied through nginx) which would cause a `git pull && bundle exec jekyll build` to happen on the box. Very simple, though it does mean managing your own infrastructure.

**Comment by dsamojlenko** [comment]
@konklone thanks for the tips!  I was looking at Federalist last week, and had had been mulling S3/Cloudfront, so glad to have confirmation.

**Comment by dsamojlenko** [comment]
The site is now hosted on S3/Cloudfront, with a certificate from LetsEncrypt

**Comment by konklone** [comment]
🎉

**Comment by konklone** [comment]
(Also small thing, but the URL associated with this repo is still `http://`.)

**Comment by dsamojlenko** [comment]
got it, thanks!
